### ISSUE TITLE
"STOP RMUF is too small" & "KeyError: 'dcs_1p086e01.dat'"

### ISSUE THREAD

**Issue by 0Hughman0** [Nebula-simulator/cstool#1]
Hi,

I am trying to build a `.mat` file for hexagonal boron nitride (hBN). I have the following `hBN.yaml`:

```
name:           hBN
density:        2.10 g/cm³

elements:
    B: { count: 1, Z: 5, M: 11.2455 g/mol }
    N:  { count: 1, Z: 7, M: 14.006 g/mol }

band_structure:
    model:      semiconductor
    valence:    6.87 eV # wickramaratne2018a
    band_gap:   5.99 eV # wickramaratne2018a
    affinity:   0.86 eV # wickramaratne2018a

optical:
    df_file:   df_hBN.dat # lee2019/ laturia2018

phonon:
    lattice:    2.51  Å  # knobloch2021
    m_eff:      2.2   m_e # knobloch2021

    longitudinal:
        c_s:    37 km/s # dodgy

    transversal:
        c_s:    37 km/s # dodgy
```

However, when I run `cstool hBN.yaml` I get the following output:

```
This is cstool version 1.0.5
Compiling material hBN
# Computing Mott cross-sections using ELSEPA.
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
STOP STOP RMUF is too small
RMUF is too small
STOP RMUF is too small
STOP RMUF is too small
Traceback (most recent call last):
  File "d:\documents\programin\conda_envs\cstool\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\documents\programin\conda_envs\cstool\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Documents\Programin\conda_envs\cstool\Scripts\cstool.exe\__main__.py", line 7, in <module>
  File "d:\documents\programin\conda_envs\cstool\lib\site-packages\cstool\apps\cstool.py", line 155, in main
    np.linspace(0.0, 1.0, 512))
  File "d:\documents\programin\conda_envs\cstool\lib\site-packages\cstool\apps\cstool.py", line 22, in compile_kieft_elastic
    mott_fn = mott_dimfp(material_params, K[K>10*units.eV], threads=4)
  File "d:\documents\programin\conda_envs\cstool\lib\site-packages\pint\registry_helpers.py", line 351, in wrapper
    return func(*args, **kwargs)
  File "d:\documents\programin\conda_envs\cstool\lib\site-packages\cstool\mott\mott.py", line 76, in mott_dimfp
    energies, threads)
  File "d:\documents\programin\conda_envs\cstool\lib\site-packages\cstool\mott\mott.py", line 59, in run_elscata_parallel
    iz_data.append(chunk_dict[get_dcs_filename(E)])
KeyError: 'dcs_1p086e01.dat'
```

I don't think it's an installation issue, because I was able to run the `copper.yaml` example successfully.

It does actually generate a `hBN.mat` file, but I'm unsure whether to trust the contents given the errors during its generation.

Let me know if you need more info.

Any help would be appreciated.

I am excited to try to make use of this tool in my research.

Hugh

**Comment by 0Hughman0** [comment]
Having dug a bit deeper. I think I'm understanding the error slightly better.

From your source, it seems that nitrogen is particularly tricky, because there is no muffin tin diameters:

https://github.com/Nebula-simulator/cstool/blob/master/cstool/mott/mott.py#L21

It seems that for the first 8 energy chunks here:

https://github.com/Nebula-simulator/cstool/blob/master/cstool/mott/mott.py#L48

elescata is not happy and getting this `STOP RMUF is too small` error, and therefore doesn't return a result.

However, the subsequent sections of code always expect each `(Z, ec)` combination to work successfully. 

Including:

https://github.com/Nebula-simulator/cstool/blob/master/cstool/mott/mott.py#L59

It does seem that for higher energies, elescata is able to produce results. So it might be possible to refactor to account for not all calls to `run_eslescata` succeeding, but might be a bit tricky.

**Comment by lvkessel** [comment]
I'm very sorry for this late reply. The problem is actually with the boron, not the nitrogen. Elscata doesn't have muffin-tin radii for either of these elements. The reason why Boron was missing from the list is that we never used it (but we did try nitrogen).

We have two options: either disable the muffin-tin model or supply our own values for the muffin-tin radius. We chose to do the former for nitrogen, as you have discovered. But maybe it's worth doing a little research to obtain reasonable values.

**Comment by 0Hughman0** [comment]
Great thanks for the response. 

Ah, so if I add Boron to `no_muffin_Z = [1, 7, 8]` i.e. `no_muffin_Z = [1, 5, 7, 8]` this will cause Elscata to use some other approach to calculate the scattering cross-section for Boron?

I will have a bit of a dig for empirical values for the Muffin tin radii for Boron and Nitrogen.

I actually managed to monkeypatch my way out of the error by suppressing exceptions caused for the early `(Z, ec)` combinations. These effectively meant that for `dimfp[iE] =  elsepa_data[iZ][iE].DCS * element.count * material_params.get_rho_n()` this would be left as zero. In hindsight maybe this wasn't the best idea... any gut instinct on how big an effect this might have on the final outcome of runs?

Thanks again, 

Hugh

**Comment by lvkessel** [comment]
Adding Boron to the `no_muffin_Z` list as you write turns off the muffin-tin model. In that case, ELSEPA will use a potential that corresponds to an isolated gas-phase atom. The muffin-tin model is a fairly simple correction to account for solid-state effects. It's good to use the muffin-tin model if we can, but disabling it is not a complete disaster.

I'll add all elements with missing muffin-tin radii to the `no_muffin_Z` list, so that cstool will at least _work_.

The patch you did has the effect of disabling elastic scattering for electrons in the energy range where the DIMFP variable is zero. Roughly speaking, elastic scattering is responsible for deflecting electrons and inelastic scattering makes them lose energy (though there is a very small amount of deflection there too). With your patch, all electrons in the range of zero DIMFP will be going pretty much straight on and lose energy, without also turning around like they should.

Whether the effect on your results is big or not depends on the energy of your primary electrons. If that falls within the zero DIMFP range, all primary electrons will penetrate way too deeply. You will have zero (or very few) high-energy backscattered electrons and a somewhat reduced amount of secondary electrons. If your primary electron energy was higher than this zero-range, the effect may actually be quite small. The reason is that the high-energy backscattered electrons are unaffected because, if they escape the sample, they usually have an energy quite close to that of the incident electron beam. Secondary electrons have mostly <50 eV energy when they are created, and we don't use ELSEPA in that energy range, so they are also unaffected. The electrons of intermediate energy, where the patch has its effect, are barely relevant in that situation.

**Comment by 0Hughman0** [comment]
Thanks for the detailed response!

I had a bit of a dive into the ELSEPA/ cstool source and couldn't work out how to feed in my own muffin tin radii, I have found some for hBN in the literature. 

Interesting, sounds like I might have gotten lucky there. The beam energy was 1-5keV and I think these errors were for the lower energy end, can't remember exactly. I think I did get fairly sensible looking results. 

In any case, much better to do this properly!

**Comment by lvkessel** [comment]
Yeah, I'll try to add the necessary functionality so you can set custom muffin-tin radii via the .yaml configuration file.

As a quick fix in the meantime, seeing as you're not averse to changing the source code, you can hardcode your muffin-tin radii in https://github.com/Nebula-simulator/cstool/blob/master/cstool/mott/mott.py#L21. (I am arbitrarily picking 1e-8 cm and 3*bohr radius as examples.)
```
no_muffin_Z = [1, 8] # Remove 5 and 7 from this one

muffin_R = {
    5: 1e-8 * units.cm,
    7: 3 * units.bohr_radius
}

settings = elscata_settings(energies, Z,
	IHEF=0,
	MCPOL=2,
	MUFFIN=False if Z in no_muffin_Z else True,
	RMUF=muffin_R.get(Z, None))
```

**Comment by 0Hughman0** [comment]
Thanks! 

This snippet did the trick.
